// @flow

export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_CANCEL = 'FETCH_DATA_CANCEL';
export const FETCH_DATA_TYPE = 'FETCH_DATA_TYPE';

export const KEYCHAIN_DATA_ERROR = 'KEYCHAIN_DATA_ERROR';
export const KEYCHAIN_DATA_REQUEST = 'KEYCHAIN_DATA_REQUEST';
export const KEYCHAIN_DATA_SUCCESS = 'KEYCHAIN_DATA_SUCCESS';
export const KEYCHAIN_DATA_SAVE = 'KEYCHAIN_DATA_SAVE';

export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_UNSYNC = 'USER_DATA_UNSYNC';
export const USER_ALL_MATCHES ='USER_ALL_MATCHES';
export const USER_PUSH_ID = 'USER_PUSH_ID';
export const USER_SET_NAME =  'USER_SET_NAME';
export const USER_SET_PURCHASE = 'USER_SET_PURCHASE';

export const MATCH_DATA_SUCCESS = 'MATCH_DATA_SUCCESS';
export const MATCH_SET_ID = 'MATCH_SET_ID';
export const MATCH_DATA_UNSYNC = 'MATCH_DATA_UNSYNC';

export const PUSH_SET_SCREEN = 'PUSH_SET_SCREEN';

export const SOUND_PLAY = 'SOUND_PLAY';
export const SOUND_PLAY_MUSIC = 'SOUND_PLAY_MUSIC';
export const SOUND_STOP_MUSIC = 'SOUND_STOP_MUSIC';
export const SOUND_STOP_ALL = 'SOUND_STOP_ALL';
export const SOUND_MUTE = 'SOUND_MUTE';
export const MUSIC_MUTE = 'MUSIC_MUTE';

export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const PROFILE_SET_ID = 'PROFILE_SET_ID';

export const LEADER_DATA_TOTAL = 'LEADER_DATA_TOTAL';
export const LEADER_DATA_WEEKLY = 'LEADER_DATA_WEEKLY';
export const LEADER_DATA_USER = 'LEADER_DATA_USER';
export const LEADER_DATA_EMPTY = 'LEADER_DATA_EMPTY';

export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_SET_NAME = 'SEARCH_SET_NAME';
